import { AlertTriangle, ArrowDownLeft, ArrowUpRight, HandCoins, Pencil, ReceiptText, RotateCcw } from 'lucide-react';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardHeader } from '../../components/ui/Card';
import { EmptyState } from '../../components/ui/States';
import { formatEgp } from '../../core/lib/profitability';
import type { Obligation, Partner, Project, Transaction } from '../../core/types/domain';
import type { Settlement } from '../settlements/types';
import type { SettlementAllocation } from '../settlement-allocations/types';
import { getOutstandingEgp } from './obligationQueries';
import type { ObligationFilters, TransactionFilters } from './hubModel';

export function FinanceOverviewView({ overview, locale, onSettle }: { overview: ReturnType<typeof import('./hubModel').computeFinanceOverview>; locale: 'ar' | 'en'; onSettle: (item: Obligation) => void }) {
  const metrics = [
    [locale === 'ar' ? 'الإيرادات' : 'Income', overview.incomeEgp, 'text-success'],
    [locale === 'ar' ? 'المصروفات' : 'Expenses', overview.expenseEgp, 'text-danger'],
    [locale === 'ar' ? 'ذمم مدينة مفتوحة' : 'Open receivables', overview.receivablesEgp, ''],
    [locale === 'ar' ? 'ذمم دائنة مفتوحة' : 'Open payables', overview.payablesEgp, ''],
    [locale === 'ar' ? 'التعرض النقدي' : 'Cash exposure', overview.cashExposureEgp, 'text-warning'],
  ] as const;
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{metrics.map(([label, value, color]) => <Card key={label}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-bold ${color}`}>{formatEgp(value, true)} EGP</p></CardContent></Card>)}</div><Card><CardHeader><h2 className="font-bold">{locale === 'ar' ? 'قائمة التحصيل والسداد' : 'Collection and payment queue'}</h2></CardHeader><CardContent>{overview.actionable.length ? <div className="space-y-2">{overview.actionable.slice(0, 8).map((item) => <button key={item.id} type="button" onClick={() => onSettle(item)} className="min-h-11 w-full rounded-xl border p-3 text-start"><strong>{item.direction}</strong><span className="block text-xs text-muted-foreground">{formatEgp(getOutstandingEgp(item))} EGP · {item.due_date ?? '—'}</span></button>)}</div> : <EmptyState title={locale === 'ar' ? 'لا توجد ذمم قابلة للتسوية' : 'No settleable obligations'} description="" icon={HandCoins} />}</CardContent></Card></div>;
}

export function TransactionsWorkspace({ items, projects, partners, filters, locale, onFilters, onCreate, onEdit, onInspect }: { items: Transaction[]; projects: Project[]; partners: Partner[]; filters: TransactionFilters; locale: 'ar' | 'en'; onFilters: (filters: TransactionFilters) => void; onCreate: () => void; onEdit: (item: Transaction) => void; onInspect: (item: Transaction) => void }) {
  const projectById = new Map(projects.map((item) => [item.id, item]));
  const partnerById = new Map(partners.map((item) => [item.id, item]));
  return <Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">{locale === 'ar' ? 'دفتر المعاملات' : 'Transaction ledger'}</h2><Button onClick={onCreate} className="min-h-11">{locale === 'ar' ? 'معاملة جديدة' : 'New transaction'}</Button></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><select value={filters.direction ?? 'all'} onChange={(event) => onFilters({ ...filters, direction: event.target.value as Transaction['direction'] | 'all' })} className="min-h-11 rounded-xl border bg-background px-3"><option value="all">All directions</option><option value="income">Income</option><option value="expense">Expense</option></select><input type="date" value={filters.dateFrom ?? ''} onChange={(event) => onFilters({ ...filters, dateFrom: event.target.value || undefined })} className="min-h-11 rounded-xl border bg-background px-3" /><input type="date" value={filters.dateTo ?? ''} onChange={(event) => onFilters({ ...filters, dateTo: event.target.value || undefined })} className="min-h-11 rounded-xl border bg-background px-3" /><Button variant="secondary" onClick={() => onFilters({})}>{locale === 'ar' ? 'مسح' : 'Clear'}</Button></div><div className="space-y-2">{items.map((item) => { const Icon = item.direction === 'income' ? ArrowUpRight : ArrowDownLeft; return <article key={item.id} className="flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center"><button type="button" onClick={() => onInspect(item)} className="min-h-11 flex-1 text-start"><span className="flex items-center gap-2"><Icon className="h-4 w-4" /><strong>{item.description || item.category}</strong><Badge tone={item.direction === 'income' ? 'positive' : 'negative'}>{item.direction}</Badge></span><span className="mt-1 block text-xs text-muted-foreground">{projectById.get(item.project_id)?.name_ar ?? item.project_id} · {item.partner_id ? partnerById.get(item.partner_id)?.name_ar ?? item.partner_id : '—'} · {item.transaction_date}</span></button><strong className={item.direction === 'income' ? 'text-success' : 'text-danger'}>{formatEgp(item.amount_egp)} EGP</strong><Button variant="secondary" size="sm" onClick={() => onEdit(item)} className="min-h-11"><Pencil className="h-4 w-4" />{locale === 'ar' ? 'تعديل' : 'Edit'}</Button></article>; })}</div></CardContent></Card>;
}

export function ObligationsWorkspace({ items, partners, filters, locale, onFilters, onCreate, onEdit, onInspect, onSettle }: { items: Obligation[]; partners: Partner[]; filters: ObligationFilters; locale: 'ar' | 'en'; onFilters: (filters: ObligationFilters) => void; onCreate: () => void; onEdit: (item: Obligation) => void; onInspect: (item: Obligation) => void; onSettle: (item: Obligation) => void }) {
  const partnerById = new Map(partners.map((item) => [item.id, item]));
  return <Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><h2 className="font-bold">{locale === 'ar' ? 'الذمم' : 'Obligations'}</h2><Button onClick={onCreate}>{locale === 'ar' ? 'ذمة جديدة' : 'New obligation'}</Button></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><select value={filters.direction ?? 'all'} onChange={(event) => onFilters({ ...filters, direction: event.target.value as Obligation['direction'] | 'all' })} className="min-h-11 rounded-xl border bg-background px-3"><option value="all">All</option><option value="receivable">Receivable</option><option value="payable">Payable</option></select><select value={filters.status ?? 'all'} onChange={(event) => onFilters({ ...filters, status: event.target.value as Obligation['status'] | 'all' })} className="min-h-11 rounded-xl border bg-background px-3"><option value="all">All statuses</option><option value="open">Open</option><option value="partial">Partial</option><option value="settled">Settled</option><option value="disputed">Disputed</option><option value="written_off">Written off</option></select><select value={filters.aging ?? 'all'} onChange={(event) => onFilters({ ...filters, aging: event.target.value as ObligationFilters['aging'] })} className="min-h-11 rounded-xl border bg-background px-3"><option value="all">All aging</option><option value="overdue">Overdue</option><option value="not-due">Not due</option></select></div><div className="space-y-2">{items.map((item) => <article key={item.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><button type="button" onClick={() => onInspect(item)} className="min-h-11 flex-1 text-start"><span className="flex flex-wrap gap-2"><strong>{partnerById.get(item.partner_id)?.name_ar ?? item.partner_id}</strong><Badge tone={item.direction === 'receivable' ? 'positive' : 'negative'}>{item.direction}</Badge><Badge tone="neutral">{item.status}</Badge></span><span className="mt-1 block text-xs text-muted-foreground">{item.due_date ?? '—'} · {locale === 'ar' ? 'المتبقي' : 'Remaining'} {formatEgp(getOutstandingEgp(item))} EGP</span></button><div className="flex gap-2"><Button variant="secondary" size="sm" onClick={() => onEdit(item)}><Pencil className="h-4 w-4" />{locale === 'ar' ? 'تعديل' : 'Edit'}</Button>{(item.status === 'open' || item.status === 'partial') && <Button size="sm" onClick={() => onSettle(item)}><HandCoins className="h-4 w-4" />{locale === 'ar' ? 'تحصيل/سداد' : 'Settle'}</Button>}</div></div></article>)}</div></CardContent></Card>;
}

export function SettlementsWorkspace({ settlements, allocations, locale, onReverse }: { settlements: Settlement[]; allocations: SettlementAllocation[]; locale: 'ar' | 'en'; onReverse: (item: Settlement) => void }) {
  return <Card><CardHeader><h2 className="font-bold">{locale === 'ar' ? 'التسويات والتوزيعات' : 'Settlements and allocations'}</h2><p className="text-xs text-muted-foreground">{locale === 'ar' ? 'التسوية حركة نقدية، والتوزيع أثرها على الذمم. يبقيان سجلًا واحدًا قابلًا للمراجعة.' : 'A settlement is cash movement; allocations apply it to obligations. Both remain auditable.'}</p></CardHeader><CardContent><div className="space-y-3">{settlements.map((item) => { const itemAllocations = allocations.filter((allocation) => allocation.settlement_id === item.id); return <article key={item.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start"><div className="flex-1"><div className="flex flex-wrap gap-2"><strong>{formatEgp(item.amount_egp)} EGP</strong><Badge tone={item.status === 'active' ? 'positive' : 'neutral'}>{item.status}</Badge></div><p className="text-xs text-muted-foreground">{item.settlement_date} · {item.payment_method} · {item.reference_number ?? item.id}</p><div className="mt-3 space-y-1">{itemAllocations.map((allocation) => <p key={allocation.id} className="text-xs"><ReceiptText className="me-1 inline h-3.5 w-3.5" />{allocation.obligation_id}: {formatEgp(allocation.allocated_amount_egp)} EGP</p>)}</div>{item.reversal_reason && <p className="mt-2 text-xs text-danger"><AlertTriangle className="me-1 inline h-3.5 w-3.5" />{item.reversal_reason}</p>}</div>{item.status === 'active' && <Button variant="secondary" onClick={() => onReverse(item)}><RotateCcw className="h-4 w-4" />{locale === 'ar' ? 'عكس' : 'Reverse'}</Button>}</div></article>; })}</div></CardContent></Card>;
}
